PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?useIntentionMappings WHERE { 
    
	<CLASS_URL> owl:equivalentClass ?useIntentionMappings.
    FILTER (!isBlank(?useIntentionMappings))                      
}